### ISSUE TITLE
Reloading configuration breaks tablist display

### ISSUE THREAD

**Issue by Andre601** [CodeCrafter47/AdvancedTabOverlay#10]
When using this specific configuration and reloading the plugin (After minor visual changes have been made) will the tab list appear broken, with the player's skin being at the very bottom and not any name or whatever being displayed.

The only thing displayed are:
- The first 3 slots (world, rank and ping)
- Empty slots (Spacers?)
- The last 3 (or 6?) slots

Config (default.yml):
```yaml
showTo: all
priority: 0

showHeaderFooter: true
header:
- "&cWelcome &f${viewer name}"
- "&eW&celcome &f${viewer name}"
- "&eWe&clcome &f${viewer name}"
- "&eWel&ccome &f${viewer name}"
- "&eWelc&come &f${viewer name}"
- "&eWelco&cme &f${viewer name}"
- "&eWelcom&ce &f${viewer name}"
- "&eWelcome &f${viewer name}"
- "&cW&eelcome &f${viewer name}"
- "&cWe&elcome &f${viewer name}"
- "&cWel&ecome &f${viewer name}"
- "&cWelc&eome &f${viewer name}"
- "&cWelco&eme &f${viewer name}"
- "&cWelcom&ee &f${viewer name}"
- "&cWelcome &f${viewer name}"
headerAnimationUpdateInterval: 0.2
footer:
- |-
  &6Line 1
  &eLine 2
- |-
  &eLine 1
  &6Line 2
footerAnimationUpdateInterval: 0.5

playerSets:
  all_players: all
customPlaceholders:
  afk_tag:
    !conditional
    condition: ${player essentials_afk}
    true: "&7|&oaway"
    false: ""
  viewer_colored_ping0:
    !conditional
    condition: ${viewer ping} < 50
    true: "&a${viewer ping}"
    false: "&e${viewer ping}"
  viewer_colored_ping:
    !conditional
    condition: ${viewer ping} < 150
    true: ${viewer_colored_ping0}
    false: "&c${viewer ping}"

hiddenPlayers: VISIBLE_TO_ADMINS

type: FIXED_SIZE
size: 60

defaultIcon: colors/dark_gray.png
defaultPing: 1000

components:
- {text: "&cWorld: &6${viewer world}", icon: "default/server.png", ping: 0}
- {text: "&cRank: &6${viewer vault_primary_group}", icon: "default/rank.png", ping: 0}
- {text: "&cPing: ${viewer_colored_ping}ms", icon: "default/ping.png", ping: 0}
- !players_by_world
  playerSet: all_players
  worldHeader:
  - {text: "", icon: "colors/dark_gray.png", ping: 1000}
  - {text: "", icon: "colors/dark_gray.png", ping: 1000}
  - {text: "", icon: "colors/dark_gray.png", ping: 1000}
  - {text: "&e&n${world} &f&o(${world player_count})", icon: "colors/yellow.png", ping: 0}
  playerComponent: "${player name}${afk_tag}"
  morePlayersComponent: {text: "&7... and &e${other_count} &7others", icon: "colors/gray.png", ping: 0}
- !spacer
- {text: "", icon: "colors/dark_gray.png", ping: 1000}
- {text: "", icon: "colors/dark_gray.png", ping: 1000}
- {text: "", icon: "colors/dark_gray.png", ping: 1000}
- {text: "&cTime: &6${time H:mm:ss}", icon: "default/clock.png", ping: 0}
- {text: "&cPlayers: &6${playerset:all_players size}", icon: "default/players.png", ping: 0}
- {text: "&cBalance: &60,00", icon: "default/balance.png", ping: 0}
```

Additional things to point out:
- I do not have any other tab list configuration saved.
- Server is PaperMC 1.16.2 (Build 184 as of this issue)
- Only installed plugins are AdvancedTabOverlay, LuckPerms, Vault and ProtocolLib (All latest release (And latest dev build in case of ProtocolLib)
- Absolutely no warning and/or errors appear in console.
