### ISSUE TITLE
Spectator Mode Time Outs

### ISSUE THREAD

**Issue by Roshanxy** [CodeCrafter47/AdvancedTabOverlay#18]
**What Happens?**
In the config.yml I have it set to;
disableCustomTabListForSpectators: false

Then..

User goes into spectator mode > Tablist gets messed up > User reloads config > Spectator mode players get timed out instantly and will constantly time out upon joining the server until their gamemode is put back to survival or creative

Or

User goes into spectator mode > Tablist gets messed up > after some time user gets timed out and can't log in again, just like the one above ^ Works fine after being put into either survival or creative

Tried version 1.2.3 and 1.3.0

This server is running Purpur version git-Purpur-1053 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Heres me in spectator mode
![image](https://user-images.githubusercontent.com/45039943/115126162-67971a00-9fcd-11eb-918b-7913e9b4c696.png)

Heres how it looks in creative or survival
![image](https://user-images.githubusercontent.com/45039943/115126305-5bf82300-9fce-11eb-8ca4-22aad52e61a2.png)

**How is it supposed to work?**
Heres me in spectator mode but using the bungee variant of this plugin with the same tablist .yml config, works perfectly fine even in spectator mode and after reloading it.
![image](https://user-images.githubusercontent.com/45039943/115126185-8ac1c980-9fcd-11eb-959d-a7e3d7632507.png)

Heres one of my alts timing out (after going into spectator mode and reloading the config via the console) on a VPS, this also happens with my main account on my main pc
![image](https://user-images.githubusercontent.com/45039943/115126214-b1800000-9fcd-11eb-9de8-1c677215a430.png)

```
showTo: all
priority: 1

showHeaderFooter: true
header: "&dWelcome ${purp ${viewer name}}"
footer: "${purp IP}"

hiddenPlayers: VISIBLE

playerSets:
  all_players: all
  users: ${player permission tablist.users}

type: FIXED_SIZE
size: 80

defaultIcon: colors/dark_gray.png
defaultPing: 1000

components:
- !table
  columns:
    0-3:
        - {text: "&5&lPlayers: &b${playerset:all_players size}", icon: "default/players.png", ping: 0}
        - {text: "&5&lPing: ${viewer_colored_ping}ms", icon: "default/ping.png", ping: 0}
        - {text: "&5&lTPS&5: ${colors ${viewer server tps 1.0}}", icon: "default/ping.png", ping: 0}
        - {text: "&5&lTime: &b${time H:mm:ss}", icon: "default/clock.png", ping: 0}
        - !players
          playerSet: all_players
          playerComponent: "&b${player name}${afk_tag}"
          morePlayersComponent: {text: "&7... and &5${other_count} &7others", icon: "colors/gray.png", ping: 10}
customPlaceholders:
  afk_tag:
    !conditional
    condition: ${player essentials_afk}
    true: "&7|&oaway"
    false: ""
  viewer_colored_ping:
    !conditional
    condition: "${viewer ping} < 150"
    true: ${viewer_colored_ping0}
    false: "&d${viewer ping}"
  viewer_colored_ping0:
    !conditional
    condition: "${viewer ping} < 50"
    true: "&a${viewer ping}"
    false: "&5${viewer ping}"
  colors:
    !color_animation
    colors: ['#a1ffec', '#67eaca', '#12d3cf', '#efbbff', '#d896ff', '#be29ec', '#660066', '#8a008a', '#c900c9', '#ff00ff', '#ff47ff']
    distance: 16
    speed: 2
  purp:
    !color_animation
    colors: ['#efbbff', '#d896ff', '#be29ec', '#660066', '#8a008a', '#c900c9', '#ff00ff', '#ff47ff']
    distance: 16
    speed: 2
```
<details>
  <summary>Plugins</summary>
Plugins (18): AntiNetherRoof*, BookFix, ChatCo, Help*, IllegalStack, LuckPerms, Matrix, OpenInv, PlaceholderAPI, PluginHiderPlus*, ProtocolLib, RandomSpawn, SuggestionBlocker, SuicideKill*, Vault, ViaBackwards, ViaVersion, Worldstats*

_ChatCo, Help and RandomSpawn are custom but not super complicated_
</details>
