### ISSUE TITLE
Unable to load icon

### ISSUE THREAD

**Issue by Andre601** [CodeCrafter47/AdvancedTabOverlay#2]
I for some reason are unable to load a tablist because the icon I set is not allowed.
![image](https://user-images.githubusercontent.com/11576465/65242910-85498800-dae7-11e9-8bfe-3309f724d07f.png)

The error says the icon has to be either a username, uuid or png image file.
However, I tried `${viewer name}`, `${viewer uuid}` and just to test it also `${viewer skin}` but none of these worked.

The current component is
```
- {text: " ${viewer name}", icon: "${viewer name}", ping: "${viewer ping}"}
```

**Comment by CodeCrafter47** [comment]
`icon: "${viewer skin}"` is supposed to work.

**Comment by Andre601** [comment]
It sadly doesn't

I also receive this error:
![image](https://user-images.githubusercontent.com/11576465/65244562-24bc4a00-daeb-11e9-97d1-ec4d41658c1a.png)

And I do have Vault and a supported perm plugin (LuckPerms) installed.

**Comment by CodeCrafter47** [comment]
Are you sure you do not want to use `${viewer vault_primary_group}` at the point where the error occurs?

**Comment by Andre601** [comment]
I now realize what the issue is.
I use the placeholder at two points in the tablist for both player and viewer, so I have to change it to have an argument.

**Comment by CodeCrafter47** [comment]
That makes sense. Probably the error message should be more specific in this case.

If tested the `icon: "${viewer skin}"` and it works fine. Make sure you do not have any extra white-spaces before/ after the placeholder as I think that would break it.

**Comment by Andre601** [comment]
The ${viewer skin} error also doesn't seem to happen on the production server which is kinda weird, but I mean when it works... 🤷‍♂

**Comment by Andre601** [comment]
But (and this is really confusing) does the tablist show the icon on the slot, where it should be shown, but also on the last slot in the tablist where it shouldn't
![2019-09-19_14 46 49](https://user-images.githubusercontent.com/11576465/65245237-80d39e00-daec-11e9-8d59-fd0f531631cd.png)

Current configuration:
```yaml
components:
- {text: " ${group viewer}${viewer name}", icon: "${viewer skin}", ping: "${viewer ping}"}
- {}
- !players
  playerSet: all_players
  playerOrder: vault_primary_group_weight desc, name
  playerComponent: "${group player}${player name}"
  morePlayersComponent: {text: "&7+${other_count} more", icon: "colors/gray.png", ping: 0}
- {text: "&8&m---------------"}
- !animated
  interval: 5
  components:
  - {text: " &9Discord:"}
  - {text: " &aMusic:"}
  - {text: " &bWarps:"}
- !animated
  interval: 5
  components:
  - {text: " &7/Discord"}
  - {text: " &7/audio"}
  - {text: " &7/warps"}
```
